### ISSUE TITLE
Integrate MSLFootballField.cpp into MSLWorldModel.cpp

### ISSUE THREAD

**Issue by StephanOpfer** [carpe-noctem-cassel/cnc-msl#3]
1. Make all methods non-static
2. Integrate it into the WorldModel, so that you can use it like the obstacles: wm.field->foo()
3. If the Vision is independent from the MSLWorldModel.cpp, keep the Singleton (MSLFootballField.getInstance()), in order to keep that independence.

**Comment by StefanJakob** [comment]
MSLFootball field is now available via WorldModel and is non-static
removed Field from Globals.conf and created FootballField.conf
adapted the classes which needed the configs
